apiVersion: v1
kind: ConfigMap
metadata:
  name: two-sum
data:
  spring.profiles.active: "cloud"
  ALGORITHM: "brute-force" # can be one of hash, two-pointers, brute-force
  _JAVA_OPTIONS: "-XX:+UseG1GC -Xmx32m -Xms32m -XX:NewSize=16m -XX:MaxNewSize=16m -XX:MaxGCPauseMillis=500 -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -XX:+UseStringDeduplication -XX:G1ReservePercent=10"
