apiVersion: v1
kind: ConfigMap
metadata:
  name: two-sum
data:
  spring.profiles.active: "cloud"
  ALGORITHM: "two-pointers" # can be one of hash, two-pointers, brute-force
  _JAVA_OPTIONS: "-XX:+UseG1GC -Xmx48m -Xms48m -XX:NewSize=32m -XX:MaxNewSize=32m -XX:+UseStringDeduplication -XX:G1ReservePercent=10 -Xlog:gc*:file=gc.log:time:filecount=9,filesize=20M"
