apiVersion: v1
kind: ConfigMap
metadata:
  name: two-sum
data:
  spring.profiles.active: "cloud"
  ALGORITHM: "brute-force" # can be one of hash, two-pointers, brute-force
  _JAVA_OPTIONS: "-XX:+UseG1GC -Xmx96m -Xms96m -XX:NewSize=64m -XX:MaxNewSize=64m -XX:+UseStringDeduplication -XX:G1ReservePercent=10 -Xlog:gc*,safepoint=info:file=gc_%p_%t.log:time,uptimemillis:filecount=4,filesize=50M"
