apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: two-sum
  name: two-sum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-sum
  template:
    metadata:
      labels:
        app: two-sum
    spec:
      containers:
      - image: brandonbenham/two-sum
        name: two-sum
        resources: {}
        ports:
          - containerPort: 8080
        resources: {}
        envFrom:
          - configMapRef:
              name: two-sum
status: {}
