apiVersion: v1
kind: Pod
metadata:
  labels:
    run: k6-influxdb-automation
  name: k6-influxdb-automation
spec:
  containers:
  - image: brandonbenham/k6-influxdb-automation
    name: k6-influxdb-automation
    env:
      - name: K6_INFLUXDB_ORGANIZATION
        value: "automation"
      - name: K6_INFLUXDB_BUCKET
        value: "response-time-data"
      - name: K6_INFLUXDB_TOKEN
        # IKS:
        #value: "gJ3ELwra9AIIFnsCy8ZEQgMBSgpQpXx9koyzBe3S0VSZq_JCylHmYt6KOxy3jNFWeZv6nsW28D--I0IRUCvPzA=="
        # AKS:
        value: "gW8I85bMAFF2NfCpAWsTiW55k3623u8_q8YVjvj9GLhnIsDJAD2gSbqLl6wHMzI7kgMB_SATNYF8tXnRuNppwA=="
      - name: K6_VUS
        value: "10"
      - name: K6_DURATION
        value: "300s"
      - name: TEST_NAME
        value: "two-sum"
    resources: {}
    command:
       - "k6"
       - "run"
       - "-o"
       - "xk6-influxdb=http://influxdb:8086"
       - "--insecure-skip-tls-verify"
       - "/js/driver.js"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
