apiVersion: v1
kind: Pod
metadata:
  labels:
    run: two-sum
  name: two-sum
spec:
  containers:
  - image: brandonbenham/two-sum
    name: two-sum
    ports:
      - containerPort: 8080
    resources: {}
    envFrom:
      - configMapRef:
          name: two-sum
  dnsPolicy: ClusterFirst
