name: Java CI with Maven, Docker, and Kubernetes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-south
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: us.icr.io
  IMAGE_NAME: iks-test
  IKS_CLUSTER: mycluster-dal10-u3c.2x4
  DEPLOYMENT_NAME: two-sum
  PORT: 5001

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#    - name: Build the Docker image
#      run: docker build . --file src/main/resources/docker-resources/Dockerfile --tag brandonbenham/two-sum
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: brandonbenham/two-sum
        #labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ./src/main/resources/docker-resources/Dockerfile
    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        #ibmcloud plugin install -f container-registry
    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
        #ibmcloud cr region-set "${IBM_CLOUD_REGION}"
        #ibmcloud cr login
    # Deploy the Docker image to the IKS cluster
    - name: Deploy to IKS
      run: |
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl config current-context
        #kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
        kubectl apply -f src/main/resources/kube-resources/config-map.yaml
        kubectl apply -f src/main/resources/kube-resources/pod.yaml
        #kubectl rollout status pod/$DEPLOYMENT_NAME
        kubectl apply -f src/main/resources/kube-resources/service.yaml
        kubectl get services -o wide
        kubectl apply -f src/main/resources/kube-resources/k6.yaml
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Run seasonal forest
      run: |
        curl --header "Content-type: application/json" http://seasonal-forest-analyzer.mycluster-dal10-u3-598878-b9d24b92a5dc610f4beac458524dd8a3-0000.us-south.containers.appdomain.cloud/v1/analyze -d '{"date":"2023-10-22T21:40:20.1103379Z", "mode":"training", "testName":"two-sum"}'
        kubectl delete pod k6-influxdb-automation
