name: Java CI with Maven, Docker, and Kubernetes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-south
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: us.icr.io
  IMAGE_NAME: iks-test
  IKS_CLUSTER: mycluster-dal10-u3c.2x4
  DEPLOYMENT_NAME: two-sum
  PORT: 5001

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: brandonbenham/two-sum
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ./src/main/resources/docker-resources/Dockerfile
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        #ibmcloud plugin install -f container-registry
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
    - name: Deploy system-under-test to IKS
      run: |
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl config current-context
        kubectl apply -f src/main/resources/kube-resources/config-map.yaml
        kubectl apply -f src/main/resources/kube-resources/deployment.yaml
        kubectl apply -f src/main/resources/kube-resources/service.yaml
        kubectl rollout restart deployment two-sum
        kubectl rollout status deployment two-sum
        kubectl get services -o wide
        kubectl get nodes -o wide
    - name: Sleep until restart completes
      run: sleep 20s
      shell: bash
    - name: Deploy K6 to IKS
      run: |
        export DATESTAMP=`date -u +"%Y-%m-%dT%H:%M:%S.%N9Z"`
        echo "DATESTAMP=$DATESTAMP" >> $GITHUB_ENV;
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl apply -f src/main/resources/kube-resources/k6.yaml
    - name: Sleep until load test finishes
      run: sleep 300s
      shell: bash
    - name: Run seasonal forest
      env:
         DATESTAMP: ${{ env.DATESTAMP }}
      run: |
        echo "datestamp: ${DATESTAMP}"
        export TEMPLATE='{"date":"%s", "mode":"live", "testName":"two-sum"}'
        echo "The template is: $TEMPLATE";
        export PAYLOAD=$(printf "$TEMPLATE" "$DATESTAMP")
        echo "The payload is: $PAYLOAD"
        RESPONSE=$(curl --slient --header "Content-type: application/json" http://seasonal-forest-analyzer.mycluster-dal10-u3-598878-b9d24b92a5dc610f4beac458524dd8a3-0000.us-south.containers.appdomain.cloud/v1/analyze -d "$PAYLOAD")
        echo $RESPONSE;
        FAIL=$(echo $RESPONSE | jq -r '.fail');
        kubectl delete pod k6-influxdb-automation
        if [[ $FAIL == "true" ]]; then
           exit 1;
        fi;
